spring:
  application:
    name: rest-with-spring-boot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: false

spring-doc:
  paths-to-match:
    - /api/person/v1/**
    - /api/book/v1/**

  swagger-ui:
    use-root-path: true

server:
  port: 8080

logging:
  level:
    root: INFO # global

cors:
  originPatterns:  http://localhost:8080,http://localhost:3000,https://google.com